// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CreateUser(ctx context.Context, id int64, username string) error {
	ret := _mock.Called(ctx, id, username)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, id, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - username string
func (_e *MockUserRepo_Expecter) CreateUser(ctx interface{}, id interface{}, username interface{}) *MockUserRepo_CreateUser_Call {
	return &MockUserRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, id, username)}
}

func (_c *MockUserRepo_CreateUser_Call) Run(run func(ctx context.Context, id int64, username string)) *MockUserRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) Return(err error) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) RunAndReturn(run func(ctx context.Context, id int64, username string) error) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDictionaryRepo creates a new instance of MockDictionaryRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDictionaryRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDictionaryRepo {
	mock := &MockDictionaryRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDictionaryRepo is an autogenerated mock type for the DictionaryRepo type
type MockDictionaryRepo struct {
	mock.Mock
}

type MockDictionaryRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDictionaryRepo) EXPECT() *MockDictionaryRepo_Expecter {
	return &MockDictionaryRepo_Expecter{mock: &_m.Mock}
}

// ExistsByID provides a mock function for the type MockDictionaryRepo
func (_mock *MockDictionaryRepo) ExistsByID(ctx context.Context, dictionaryID string) (bool, error) {
	ret := _mock.Called(ctx, dictionaryID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, dictionaryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, dictionaryID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dictionaryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDictionaryRepo_ExistsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByID'
type MockDictionaryRepo_ExistsByID_Call struct {
	*mock.Call
}

// ExistsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - dictionaryID string
func (_e *MockDictionaryRepo_Expecter) ExistsByID(ctx interface{}, dictionaryID interface{}) *MockDictionaryRepo_ExistsByID_Call {
	return &MockDictionaryRepo_ExistsByID_Call{Call: _e.mock.On("ExistsByID", ctx, dictionaryID)}
}

func (_c *MockDictionaryRepo_ExistsByID_Call) Run(run func(ctx context.Context, dictionaryID string)) *MockDictionaryRepo_ExistsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDictionaryRepo_ExistsByID_Call) Return(b bool, err error) *MockDictionaryRepo_ExistsByID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDictionaryRepo_ExistsByID_Call) RunAndReturn(run func(ctx context.Context, dictionaryID string) (bool, error)) *MockDictionaryRepo_ExistsByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionsRepo creates a new instance of MockSubscriptionsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionsRepo {
	mock := &MockSubscriptionsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionsRepo is an autogenerated mock type for the SubscriptionsRepo type
type MockSubscriptionsRepo struct {
	mock.Mock
}

type MockSubscriptionsRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionsRepo) EXPECT() *MockSubscriptionsRepo_Expecter {
	return &MockSubscriptionsRepo_Expecter{mock: &_m.Mock}
}

// IsSubscribedByUser provides a mock function for the type MockSubscriptionsRepo
func (_mock *MockSubscriptionsRepo) IsSubscribedByUser(ctx context.Context, userID int64, dictionaryID string) (bool, error) {
	ret := _mock.Called(ctx, userID, dictionaryID)

	if len(ret) == 0 {
		panic("no return value specified for IsSubscribedByUser")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return returnFunc(ctx, userID, dictionaryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = returnFunc(ctx, userID, dictionaryID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, dictionaryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionsRepo_IsSubscribedByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSubscribedByUser'
type MockSubscriptionsRepo_IsSubscribedByUser_Call struct {
	*mock.Call
}

// IsSubscribedByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - dictionaryID string
func (_e *MockSubscriptionsRepo_Expecter) IsSubscribedByUser(ctx interface{}, userID interface{}, dictionaryID interface{}) *MockSubscriptionsRepo_IsSubscribedByUser_Call {
	return &MockSubscriptionsRepo_IsSubscribedByUser_Call{Call: _e.mock.On("IsSubscribedByUser", ctx, userID, dictionaryID)}
}

func (_c *MockSubscriptionsRepo_IsSubscribedByUser_Call) Run(run func(ctx context.Context, userID int64, dictionaryID string)) *MockSubscriptionsRepo_IsSubscribedByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionsRepo_IsSubscribedByUser_Call) Return(b bool, err error) *MockSubscriptionsRepo_IsSubscribedByUser_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSubscriptionsRepo_IsSubscribedByUser_Call) RunAndReturn(run func(ctx context.Context, userID int64, dictionaryID string) (bool, error)) *MockSubscriptionsRepo_IsSubscribedByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockSubscriptionsRepo
func (_mock *MockSubscriptionsRepo) Subscribe(ctx context.Context, userID int64, dictionaryID string) (bool, error) {
	ret := _mock.Called(ctx, userID, dictionaryID)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return returnFunc(ctx, userID, dictionaryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = returnFunc(ctx, userID, dictionaryID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, dictionaryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionsRepo_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockSubscriptionsRepo_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - dictionaryID string
func (_e *MockSubscriptionsRepo_Expecter) Subscribe(ctx interface{}, userID interface{}, dictionaryID interface{}) *MockSubscriptionsRepo_Subscribe_Call {
	return &MockSubscriptionsRepo_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, userID, dictionaryID)}
}

func (_c *MockSubscriptionsRepo_Subscribe_Call) Run(run func(ctx context.Context, userID int64, dictionaryID string)) *MockSubscriptionsRepo_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionsRepo_Subscribe_Call) Return(b bool, err error) *MockSubscriptionsRepo_Subscribe_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSubscriptionsRepo_Subscribe_Call) RunAndReturn(run func(ctx context.Context, userID int64, dictionaryID string) (bool, error)) *MockSubscriptionsRepo_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockSubscriptionsRepo
func (_mock *MockSubscriptionsRepo) Unsubscribe(ctx context.Context, userID int64, dictionaryID string) (bool, error) {
	ret := _mock.Called(ctx, userID, dictionaryID)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return returnFunc(ctx, userID, dictionaryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = returnFunc(ctx, userID, dictionaryID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, dictionaryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionsRepo_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockSubscriptionsRepo_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - dictionaryID string
func (_e *MockSubscriptionsRepo_Expecter) Unsubscribe(ctx interface{}, userID interface{}, dictionaryID interface{}) *MockSubscriptionsRepo_Unsubscribe_Call {
	return &MockSubscriptionsRepo_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", ctx, userID, dictionaryID)}
}

func (_c *MockSubscriptionsRepo_Unsubscribe_Call) Run(run func(ctx context.Context, userID int64, dictionaryID string)) *MockSubscriptionsRepo_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSubscriptionsRepo_Unsubscribe_Call) Return(b bool, err error) *MockSubscriptionsRepo_Unsubscribe_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSubscriptionsRepo_Unsubscribe_Call) RunAndReturn(run func(ctx context.Context, userID int64, dictionaryID string) (bool, error)) *MockSubscriptionsRepo_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}
